'use client'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight, Car, Dumbbell, Hotel, MapPin, Utensils, Waves, Wifi, Phone, CalendarDays } from 'lucide-react'
import { motion } from 'framer-motion'
import { Reveal } from './Reveal'
import { images, hotelConfig } from './siteData'

const icons=[Hotel,Waves,Dumbbell,Utensils,Utensils,CalendarDays,Wifi,Car]

export function Intro(){return <section className="paper px-5 md:px-8 py-16 md:py-24"><div className="max-w-[1460px] mx-auto"><div className="grid lg:grid-cols-[.62fr_1.38fr] gap-8 items-end"><Reveal><div className="eyebrow dark">THE ESSENTIALS</div></Reveal><Reveal delay={.08}><h2 className="serif dark-title text-[clamp(43px,6.3vw,88px)] leading-[.88] tracking-[-.05em]">Your stay,<br/><i>thoughtfully considered.</i></h2></Reveal></div><div className="amenity-grid mt-14">{hotelConfig.amenities.map((a,i)=>{const Icon=icons[i]||Hotel;return <Reveal key={a} delay={i*.035}><div className="amenity-tile"><div className="amenity-photo"><Image src={[images.room,images.pool,images.architecture,images.dining,images.dining,images.lounge,images.room,images.hero][i]} alt={`${a} concept`} fill sizes="25vw" className="object-cover"/><span className="photo-shade"/></div><div className="amenity-copy"><Icon size={15}/><span>{a}</span></div></div></Reveal>})}</div></div></section>}

export function Story(){return <section className="story-wrap"><div className="story-image"><Image src={images.architecture} alt="Papua landscape concept photography" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#081619]/75 via-transparent to-[#081619]/20"/><div className="story-copy"><div className="eyebrow">TIMIKA · PAPUA TENGAH</div><h2 className="serif text-4xl md:text-6xl max-w-2xl mt-3">Stay connected to Timika.<br/>Stay comfortable.</h2><Link href="/location/" className="story-link">DISCOVER MORE <ArrowUpRight size={14}/></Link></div></div></section>}

export function Reputation(){return <section className="paper px-5 md:px-8 py-14"><div className="max-w-[1460px] mx-auto reputation"><Reveal><div className="eyebrow dark">TRUSTED BY OUR GUESTS</div><div className="serif dark-title text-6xl md:text-8xl mt-2">{hotelConfig.rating}<span className="text-xl align-middle ml-2">/ 5</span></div><div className="stars">★★★★★</div><div className="dark-muted text-xs mt-2">{hotelConfig.reviewCount} · Google reviews</div></Reveal><Reveal delay={.08}><p className="serif text-2xl md:text-3xl dark-copy">Guest feedback highlights cleanliness, helpful reception, convenient location, rooms, breakfast and facilities.</p><p className="dark-muted text-[10px] mt-5">Summary of themes only — not direct customer quotations.</p></Reveal></div></section>}

export function PageHero({eyebrow,title,sub,image}:{eyebrow:string,title:React.ReactNode,sub:string,image:string}){return <section className="page-hero px-5 md:px-8"><div className="page-hero-image"><Image src={image} alt="Hotel concept photography" fill sizes="100vw" priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#071518]/90 via-[#071518]/15 to-transparent"/></div><div className="page-hero-copy"><Reveal><div className="eyebrow">{eyebrow}</div><h1 className="serif text-[clamp(50px,8vw,112px)] leading-[.84] tracking-[-.055em] mt-4">{title}</h1><p className="max-w-xl mt-6 text-white/65 text-sm md:text-base leading-6">{sub}</p></Reveal></div></section>}

const roomFeatures=['Air conditioning','TV','Free Wi-Fi','En-suite bathroom']
export function RoomCards(){return <section className="dark-section px-5 md:px-8 py-10 md:py-20"><div className="max-w-[1460px] mx-auto"><div className="section-title"><div className="eyebrow">OUR ROOMS</div><h2 className="serif text-4xl md:text-5xl mt-3">Comfortable room and suite spaces.</h2><p>Room categories, availability and exact inclusions should be confirmed directly with the hotel.</p></div><div className="grid lg:grid-cols-2 gap-5 mt-12">{[['ROOM',images.room,'Designed for rest.'],['SUITE',images.lounge,'More space for a relaxed stay.']].map(([t,img,h],i)=><Reveal key={t} delay={i*.08}><article className="room-card"><div className="room-img"><Image src={img} alt={`${t} concept photography`} fill sizes="50vw" className="object-cover"/></div><div className="room-body"><div className="eyebrow">{t}</div><h3 className="serif text-3xl mt-2">{h}</h3><div className="feature-list">{roomFeatures.map(f=><span key={f}>{f}</span>)}{t==='SUITE'&&<span>Suite living area</span>}</div><Link href="/location/" className="pill pill-cream">ENQUIRE ABOUT THIS ROOM <ArrowUpRight size={13}/></Link></div></article></Reveal>)}</div><div className="gallery-strip mt-6"><div className="gallery-main"><Image src={images.architecture} alt="Room gallery concept" fill sizes="70vw" className="object-cover"/></div><div className="gallery-note"><div className="eyebrow">ROOM GALLERY</div><p className="serif text-2xl mt-3">Explore our rooms and spaces.</p><div className="mini-gallery"><Image src={images.room} alt="Room detail" fill sizes="25vw" className="object-cover"/></div></div></div></div></section>}

const experiences=[['01','INDOOR POOL',images.pool,'Relax and refresh in our indoor pool.'],['02','FITNESS',images.architecture,'Keep up with your routine.'],['03','BREAKFAST',images.dining,'Start your day with breakfast.'],['04','DINING',images.dining,'Enjoy good food and moments together.'],['05','CITY ACCESS',images.hero,'A convenient base to explore Timika.'],['06','24-HOUR SERVICE',images.lounge,'Our team is here for you, anytime.']]
export function ExperienceGrid(){return <section className="dark-section px-5 md:px-8 pb-16"><div className="max-w-[1460px] mx-auto experience-list">{experiences.map(([n,t,img,p],i)=><Reveal key={t} delay={i*.03}><motion.article whileHover={{scale:1.008}} className="experience-row"><Image src={img} alt={`${t} concept`} fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#071518]/85 via-[#071518]/25 to-[#071518]/50"/><div className="experience-copy"><span className="eyebrow">{n}</span><div><h2 className="serif text-3xl md:text-5xl">{t}</h2><p>{p}</p></div></div></motion.article></Reveal>)}</div></section>}

export function DiningEvents(){return <section className="dark-section px-5 md:px-8 pb-16"><div className="max-w-[1460px] mx-auto"><div className="dining-grid"><Reveal><article className="dining-feature"><Image src={images.dining} alt="Restaurant concept" fill sizes="70vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#071518]/90 to-transparent"/><div className="dining-copy"><div className="eyebrow">DINING</div><h2 className="serif text-5xl md:text-7xl mt-3">Gather around something good.</h2><p>Restaurant, bar and breakfast are part of the hotel experience. Confirm current menus and service details with the hotel.</p></div></article></Reveal><Reveal delay={.06}><article className="dining-side"><div className="side-image"><Image src={images.lounge} alt="Bar concept" fill sizes="40vw" className="object-cover"/></div><div className="side-copy"><div className="eyebrow">BAR</div><h3 className="serif text-3xl mt-2">A welcoming space for conversation and good time.</h3></div></article></Reveal></div><Reveal><article className="events-panel mt-5"><div><div className="eyebrow dark">EVENTS AT HORISON DIANA TIMIKA</div><h2 className="serif dark-title text-5xl md:text-7xl mt-3">Make space for important moments.</h2><p className="dark-copy mt-5 max-w-xl">A ballroom/event setting for meetings, celebrations and private events. Contact the hotel for current availability, layouts and capacity.</p><Link href="/location/" className="pill pill-dark-solid mt-7">ENQUIRE ABOUT EVENTS <ArrowUpRight size={13}/></Link></div><div className="events-image"><Image src={images.architecture} alt="Event venue concept" fill sizes="45vw" className="object-cover"/></div></article></Reveal></div></section>}

export function ContactPanel(){return <section className="contact-section"><div className="contact-image"><Image src={images.hero} alt="Horison Diana Timika concept exterior" fill sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-[#061417]/55"/></div><div className="contact-inner"><Reveal><div className="eyebrow">LOCATION</div><h2 className="serif text-[clamp(48px,7vw,90px)] leading-[.88] mt-3">Well placed<br/>in Timika.</h2><p className="mt-6 text-white/65 max-w-md">Easy to find. Closer to what matters.</p><div className="mt-7 text-sm text-white/70 flex gap-3"><MapPin size={17}/><span>{hotelConfig.address}</span></div><div className="mt-3 text-sm text-white/70 flex gap-3"><Phone size={17}/><span>{hotelConfig.phone}</span></div><div className="flex flex-wrap gap-3 mt-8"><a href={hotelConfig.phoneHref} className="pill pill-light"><Phone size={13}/> CALL HOTEL</a><a href={hotelConfig.whatsapp} className="pill pill-dark">WHATSAPP</a><a href={hotelConfig.directions} target="_blank" rel="noreferrer" className="pill pill-dark">GET DIRECTIONS <ArrowUpRight size={13}/></a></div></Reveal></div></section>}
